project:
  type: website
  output-dir: docs
  
website:
  title: "Katherine Goode"
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - papers.qmd
      - presentations.qmd
      - software.qmd
      - resume.Rmd
      - icon: github
        url: "https://github.com/goodekat"
      - icon: linkedin
        url: "https://www.linkedin.com/in/katherine-goode-363517a9/"
     
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

